# Generated by Django 5.1.1 on 2024-09-21 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Konfigurasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_konfigurasi', models.CharField(max_length=55)),
                ('nilai', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Pengukuran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suhu_air', models.FloatField()),
                ('ph', models.FloatField()),
                ('total_solid_dissolve', models.FloatField(null=True)),
                ('waktu_pengukuran', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
